### PR TITLE
Add template for DDD project

### LINKED ISSUE #2: Create DDD project template

### PR DESCRIPTION
**Pull request by eltjo-k**
## Add template for DDD project

The goal of the template is to facilitate the creation of an event sourced Domain Driven project, with minimum working examples of all moving parts, such as arregates, projections, policies, event store, etc, for easy adaptation to the specifics of the solution to create.

When the project is started it will complain about an empty connection string. Once a connection string is provided a sample tables for the Eventstore and a Readmodels will be automatically created. This also serves to demonstrate the regeneration of Readmodels on server startup, and the different frameworks used to read (Dapper) and write (Entity Framework) to the database.

### CODE REVIEW

**Comment by xaberue** [comment]
Hi @eltjo-k !!!

Is a great work!!! I have downloaded everything and I am trying to go through the whole template.

One initial question: The User implementation is like an example of how to deal with users here?

**Comment by Xelit3** [comment]
Since the moment, let me suggest the following changes:
- Change the name of the folder in sln "7. Testing" instead of "Test" 
- Change the same name for the template
- Add some comments at startup explaining the different things configured, for instance suggesting that the UseCors should be configured instead of leaving everything allowed.
- Add some comments at the header of the current examples, like the User impl at every layer for instance
- In the vstemplate:
  - Move description text to Name
  - In description, extend information adding technical integrations like using AspNet, Dapper, Swagger or others

**Review by xaberue — CHANGES_REQUESTED** [review]
Since the moment, let me suggest the following changes:
- Change the name of the folder in sln "7. Testing" instead of "Test" 
- Change the same name for the template
- Add some comments at startup explaining the different things configured, for instance suggesting that the UseCors should be configured instead of leaving everything allowed.
- Add some comments at the header of the current examples, like the User impl at every layer for instance
- In the vstemplate:
  - Move description text to Name
  - In description, extend information adding technical integrations like using AspNet, Dapper, Swagger or others. For instance add also that the template is focused on a DDD project using EventSourcing and CQRS

**Review by xaberue — APPROVED** [review]
Perfect work as usual @eltjo-k !

Thanks a lot

**Review by vvillena — APPROVED** [review]
Great work!

**Pull request merged**
